config/routes.rb
Kodiak::Application.routes.draw do

  get 'feed' => 'posts#feed'

  mount API::Root => '/'

  get 'posts/drafts' => 'posts#drafts', as: :drafts

  get '/posts/:id/reply'   => "posts#new_reply", as: :new_post_reply

  post '/posts/:id/reply' => "posts#reply", as: :post_reply

  resources :settings

  resources :galleries

  resources :search
  resources :attachments

  resources :posts

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  resources :users

  resources :photos

  resources :categories

  get '/archives' => 'archives#index'
  
  get '/:year' => 'archives#year', constraints: {
    year: /\d{4}/
  }, as: :year

  get '/:year/:month' => 'archives#month', constraints: {
    year: /\d{4}/,
    month: /\d{1,2}/
  }, as: :month

  get '/:year/:month/:day' => 'archives#day', constraints: {
    year: /\d{4}/,
    month: /\d{1,2}/,
    day: /\d{1,2}/
  }, as: :day

  get '/galleries/:id/photos/new' => 'photos#new', as: :gallery_photo

  root :to => "home#index"

  
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  store_accessor :configuration, :posts_per_page

  def self.get(key)
    setting = where("configuration ->> 'type' = ?", key)
    if !setting.empty?
      setting.order(id: :desc).first.configuration
    end
  end

  # does this even work?
  # now we have versioned configuration
  def self.set(hash)
    create(configuration: hash)
  end

  def self.distinct_settings(page=nil)
    page ||= 1
    settings = []
    select("DISTINCT ON(settings.id) settings.*")
      .page(page)
      .order(id: :desc)
      .map{|setting| settings << {:id => setting.id}.merge(setting.configuration)}
    settings.uniq!{|s| s['type']}
  end
end

app/controllers/settings_controller.rb
require 'pp'
class SettingsController < ApplicationController
  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  # GET /settings
  def index
    @settings = Setting.distinct_settings(params[:page])
  end

  # GET /settings/1
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  def create
    @setting = Setting.new(setting_params)

    if @setting.save
      redirect_to @setting, notice: 'Setting was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /settings/1
  def update
    if @setting.update(setting_params)
      redirect_to @setting, notice: 'Setting was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /settings/1
  def destroy
    @setting.destroy
    redirect_to settings_url, notice: 'Setting was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def setting_params
      params.require(:setting).permit!
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<%= form_for(@setting) do |f| %>
  <% if @setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% @setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :configuration %>
    <%= f.text_area :configuration, rows: 10, cols: 70, value: @setting['configuration'] ? JSON.pretty_generate(@setting['configuration']) : "" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/settings/_setting.html.erb
<%# make me a helper %>
<table>
  <tr>
    <th>Name</th>
    <th>Value</th>
  <tr>
    <td><%= setting.configuration['type'] %></td>
  </td>
   <td><pre><%=  raw JSON.pretty_generate(setting.configuration['settings']) %></pre>
  </tr>
</table>

app/views/settings/edit.html.erb
<h1>Editing setting</h1>

<%= render 'form' %>

<%= link_to 'Show', @setting %> |
<%= link_to 'Back', settings_path %>

app/views/settings/index.html.erb
<h1>Listing settings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Value</th>
      <th colspan=2>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= setting['type'] %></td>
        <td><pre><%=  raw JSON.pretty_generate(setting) %></pre></td>
        <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
        <td><%= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setting', new_setting_path %>

app/views/settings/new.html.erb
<h1>New setting</h1>
<p>Settings require the following:</p>
<ol>
  <li>type: this acts as the "key" for the setting</li>
  <li>settings: the actual key/value hash</li>
</ol>
<p>Example:</p>
<div><pre>
{
    "type": "site_images",
    "settings": {
        "banner_img": "hello.jpg"
    }
}
</pre></div>

<%= render 'form' %>

<%= link_to 'Back', settings_path %>

app/views/settings/show.html.erb
<%= render partial: @setting %>
<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>