config/routes.rb
Kodiak::Application.routes.draw do

  get 'feed' => 'posts#feed'

  mount API::Root => '/'

  get 'posts/drafts' => 'posts#drafts', as: :drafts

  get '/posts/:id/reply'   => "posts#new_reply", as: :new_post_reply

  post '/posts/:id/reply' => "posts#reply", as: :post_reply

  resources :settings

  resources :galleries

  resources :search
  resources :attachments

  resources :posts

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  resources :users

  resources :photos

  resources :categories

  get '/archives' => 'archives#index'
  
  get '/:year' => 'archives#year', constraints: {
    year: /\d{4}/
  }, as: :year

  get '/:year/:month' => 'archives#month', constraints: {
    year: /\d{4}/,
    month: /\d{1,2}/
  }, as: :month

  get '/:year/:month/:day' => 'archives#day', constraints: {
    year: /\d{4}/,
    month: /\d{1,2}/,
    day: /\d{1,2}/
  }, as: :day

  get '/galleries/:id/photos/new' => 'photos#new', as: :gallery_photo

  root :to => "home#index"

  
end

app/models/post.rb
class Post < ActiveRecord::Base
  alias_attribute :author, :user
  include Treeify
  tree_config :cols => [:title, :user_id, :body]

  include PgSearch
  include Search
  multisearchable :against => [:title, :author, :body, :category_id, :published_on],
                  :if => lambda{ |record| record.published_on != nil }

  validates :title, presence: true
  validates :body, presence: true
 
  extend Hashifiable
  extend FriendlyId
  friendly_id :title, use: :slugged
  # has many
  has_many :comments, class_name: "Post", foreign_key: "parent_id"
  has_and_belongs_to_many :tags

  # belongs to
  belongs_to :post_comments, class_name: "Post"
  belongs_to :user
  belongs_to :category
  belongs_to :parent, class_name: "Post", touch: true

  accepts_nested_attributes_for :tags, :comments, :category

  hashify :body, :category, :parent_id, 
          :title, :tags, :category, 
          :user, :comments
  paginates_per APP_CONFIG['posts_per_page']

  def has_tag?(tag)
    self.tags.include?(tag)
  end

  pg_search_scope :fast_search,
                  :against => [:title, :body],
                  :using   => {
                    tsearch: {
                      dictionary: 'english',
                      tsvector_column: 'tsv'
                    },
                    trigram: {}
                  }


   scope :posts_by_year, ->(year) { where("extract(year from published_on) = ?", year).order(published_on: :desc) }
   scope :posts_by_month, ->(year, month) { 
     posts_by_year(year).where("extract(month from published_on) = ?", month).order(published_on: :desc) 
   }


   scope :with_author, -> { eager_load(:user) }

   scope :front_page, ->(page) { with_author.where(parent: nil).where.not(published_on: nil).order(published_on: :desc).page(page) }

   scope :drafts, -> { where(published_on: nil) }

   scope :published, -> { where.not(published_on: nil) }

   scope :roots, -> { published.where(parent: nil) }

   def self.distinct_years
     order('cast(extract(year from published_on) as integer) DESC').pluck('distinct(cast(extract(year from published_on) as integer))') 
   end

   def self.year_month_pairs
     select("extract(year from published_on) as year, extract(month from published_on) as month").
     order("year desc, month desc").
     group("extract(year from published_on), extract(month from published_on)")
   end

   def self.search(params)
#     order_options =  params.has_key?('order_by')     ? 
#       { params['order_by'] => params['order_type'] } : 
#       { :published_on => 'desc'}
     PgSearch.multisearch(params['q']).page(params['page']||1)
   end

   def reply_tree
     # give build_tree an array of hashes with the AR objects serialized into a hash
     build_tree(descendents.to_a.map(&:serializable_hash))
   end

   def self.delete_search_documents
     PgSearch::Document.delete_all(:searchable_type =>"Post")
   end

   def self.rebuild_pg_search_documents
     #PgSearch::Multisearch.rebuild(Post)
     find_each { |record| record.update_pg_search_document }
   end
end

app/controllers/posts_controller.rb
require 'pp'
require 'actionpack/action_caching'
class PostsController < ApplicationController
  skip_authorize_resource :only => [:index, :show] 
  before_filter :authenticate_user!, :except => [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.front_page(params[:page])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.includes(:user, :parent).friendly.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @user = current_user
    @post = Post.new
    @post.user(@user)
    @post.published_on = DateTime.now
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.friendly.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @user = current_user
    @new_category = params[:post].delete "new_category"
    @post = @user.posts.new(params[:post])
    if !@new_category.blank?
      @post.category = Category.new(name: @new_category)
    end

    respond_to do |format|
      if @post.save
        expire_action :action => :index
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.friendly.find(params[:id])
    post_params = params[:post]
    if !post_params[:new_category].blank?
      post_params[:category] = Category.new(name: post_params.delete(:new_category))
    else
      post_params.delete(:new_category)
    end
    respond_to do |format|
      if @post.update_attributes(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.friendly.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  def reply
    @post = Post.includes(:parent).friendly.find(params[:id])
    @post.comments.create(
      user: user_signed_in? ? current_user : User.find_or_initialize(name: params[:commentor_name]),
      title: "RE: #{@post.title}", 
      body: params[:post][:body],
      category: @post.category,
      published_on: DateTime.now
    )

    respond_to do |format|
      format.html { redirect_to post_url(@post) }
      format.json { head :no_content }
    end
  end

  def new_reply
    @post = Post.friendly.find(params[:id])
  end

  def drafts
    @posts = current_user.posts.drafts.page(params[:page]||1)
  end

  def feed
    @posts = Post.roots.all.order(created_at: :desc)

    respond_to do |format|
      format.rss { render :layout => false }
    end
  end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post, multipart: true, :html => { :id => "new-post" }) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, rows: 4, cols: 60 %>
  </div>
  <div class="field">
    
    <%= f.label :category_id %><br />
    <%= f.collection_select(:category_id, Category.all, :id, :name, :prompt => 'Please select your category') %>
  </div>
  <div class="field">
    <p>Or create a new category</p>
    <input type="text" name="post[new_category]" />
  </div>
  <div class="field">
    <%= f.label :published_on %>
    <%= f.datetime_local_field :published_on %>
  </div>
  <div class="actions">
    <%= f.submit 'Create post', :id => "post-submit-btn" %>
  </div>
<% end %>
<% @deferred_content = javascript_include_tag '//tinymce.cachefly.net/4.1/tinymce.min.js' %>

app/views/posts/_page.html.erb
<%= paginate @posts %>

app/views/posts/_post.html.erb
<div class="blog-post">
  <h2 class="blog-post-title"><%= link_to post.title, post %></h2>
  <p class="blog-post-meta">
  <%= post.published_on.nil? ? "(draft)" : post.published_on.to_s(:posted_on) %> by <%= link_to (post.user.name != ""  ? post.user.name : post.user.email), user_path(post.user) %> 
    <% if post.category%>
      in <%= post.category.name %>
    <% end %>
    <% if post.parent %>
      in reply to <%= link_to post.parent.title, post_path(post.parent) %>
    <% end %>
    <%= link_to "#{post.comments.count} comments", post %>
  </p>
  <div class="blog-post-body">
    <%= raw post.body %>  
  </div>
  <hr />
  <% if can? :edit, post %>
  <div class="post-edit">
    <%= link_to 'Edit', edit_post_path(post) %>
  </div>
  <% end %>
</div>
<!-- /.blog-post -->

app/views/posts/_reply.html.erb
<% if user_signed_in? %> 
  <%= form_for(reply, url: { action: "reply" }, method: "reply") do |f| %>
    <% if reply.errors.any? %>
      <div id="error_explanation">
      <h2><%= pluralize(reply.errors.count, "error") %> prohibited this reply from being saved:</h2>

      <ul>
      <% reply.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, rows: 8, cols: 75, :value => "" %>
  </div>
  <div class="actions">
    <%= f.submit 'Create reply', :id => "reply-submit-btn" %>
  </div>
  <% end %>
  <% @deferred_content = javascript_include_tag '//tinymce.cachefly.net/4.1/tinymce.min.js' %>
<% else %>
  <%= link_to 'Sign in to reply', new_user_session_url %>
<% end %>

app/views/posts/_reply_body.html.erb
<div class="blog-post">
    <p class="blog-post-meta">
    <%= reply.published_on %> by <%= reply.author.name != "" ? reply.author.name : reply.author.email %>
    </p>
      <div class="blog-post-body">
      <%= raw reply.body %>
      </div>                                                                                                                                
    <p><%= link_to 'Reply', new_post_reply_url(reply) %></p>
    <% if reply.comments %>
      <ul class="replies">
      <% reply.comments.each do |subreply| %>
        <li>
        <%= render partial: 'posts/reply_body', locals: { reply: subreply } %>
        </li>
      <% end %>
      </ul>
    <% end %>
  </div>

app/views/posts/drafts.html.erb
<h1>Drafts</h1>
<br />
<%= render partial: @posts %>


<%= render 'posts/page' %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>
<br />
<%= render partial: @posts %>


<%= render 'posts/page' %>

app/views/posts/new.html.erb
<h1 class="category-title">New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/new_reply.html.erb
<h2>Replying to:</h2>
<%= render partial: @post %>
<%= render partial: 'reply', locals: { reply: @post } %>

app/views/posts/show.html.erb
<%= render partial: @post %>
<%= render partial: 'reply', locals: { reply: @post } %>
<br />

<p>Replies:</p>
<% if @post.comments %>
  <% @post.comments.each do |reply| %>
    <%= render partial: 'posts/reply_body', locals: { reply: reply } %>
  <% end %>
<% end %>