config/routes.rb
Kodiak::Application.routes.draw do

  get 'feed' => 'posts#feed'

  mount API::Root => '/'

  get 'posts/drafts' => 'posts#drafts', as: :drafts

  get '/posts/:id/reply'   => "posts#new_reply", as: :new_post_reply

  post '/posts/:id/reply' => "posts#reply", as: :post_reply

  resources :settings

  resources :galleries

  resources :search
  resources :attachments

  resources :posts

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  resources :users

  resources :photos

  resources :categories

  get '/archives' => 'archives#index'
  
  get '/:year' => 'archives#year', constraints: {
    year: /\d{4}/
  }, as: :year

  get '/:year/:month' => 'archives#month', constraints: {
    year: /\d{4}/,
    month: /\d{1,2}/
  }, as: :month

  get '/:year/:month/:day' => 'archives#day', constraints: {
    year: /\d{4}/,
    month: /\d{1,2}/,
    day: /\d{1,2}/
  }, as: :day

  get '/galleries/:id/photos/new' => 'photos#new', as: :gallery_photo

  root :to => "home#index"

  
end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_many :posts

  validates :name, presence: true, uniqueness: true
end

app/controllers/categories_controller.rb
require 'pp'
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  def index
    @categories = Category.all
  end

  # GET /categories/1
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      success_msg = 'Category was successfully created'
      if @category.save
        format.html { redirect_to @category, notice: success_msg }
        # the @category.to_h.merge(...) stuff should be moved to a module
        format.json { 
          render json: @category.to_h.merge(notice: success_msg), status: :created, location: @category }
        format.js { render json: @category.to_h.merge(notice: success_msg), content_type: 'text/json' }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.friendly.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def category_params
      params[:category]
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div id="category-notice"></div>
<%= form_for(@category, remote: true, :url => '/categories.json') do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
    <%= link_to 'Cancel', categories_path, :rel => "modal:close", :class => "button" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to 'Show', category %></td>
        <% if can? :edit, category %>
          <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <% end %>
        <% if can? :delete, category %>
          <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<%= render partial: 'posts/post', collection: @category.posts  %>
<% if can? :edit, @category %>
  <%= link_to 'Edit', edit_category_path(@category) %> |
<% end %>
<%= link_to 'Back', categories_path %>